// Code generated by command: go run main.go -out ../filters_amd64.s -stubs ../filters_stub_amd64.go -pkg simd. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

// func addIntoBlocks(dst []byte, src []byte)
// Requires: SSE2
TEXT ·addIntoBlocks(SB), NOSPLIT, $0-48
	MOVQ dst_base+0(FP), AX
	MOVQ src_base+24(FP), CX
	MOVQ dst_len+8(FP), DX
	ANDQ $-16, DX
	XORQ BX, BX

loop:
	CMPQ  BX, DX
	JGE   done
	MOVOU (AX)(BX*1), X0
	MOVOU (CX)(BX*1), X1
	PADDB X1, X0
	MOVOU X0, (AX)(BX*1)
	ADDQ  $0x10, BX
	JMP   loop

done:
	RET

// func subSumBlocks(dst []byte, a []byte, b []byte) uint64
// Requires: SSE2
TEXT ·subSumBlocks(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), AX
	MOVQ a_base+24(FP), CX
	MOVQ b_base+48(FP), DX
	MOVQ a_len+32(FP), BX
	ANDQ $-16, BX
	PXOR X0, X0
	PXOR X1, X1
	XORQ SI, SI

loop:
	CMPQ   SI, BX
	JGE    reduce
	MOVOU  (CX)(SI*1), X2
	MOVOU  (DX)(SI*1), X3
	PSUBB  X3, X2
	MOVOU  X2, (AX)(SI*1)
	PXOR   X3, X3
	PSUBB  X2, X3
	PMINUB X3, X2
	PSADBW X1, X2
	PADDQ  X2, X0
	ADDQ   $0x10, SI
	JMP    loop

reduce:
	MOVQ   X0, AX
	PSHUFD $0xee, X0, X0
	MOVQ   X0, CX
	ADDQ   CX, AX
	MOVQ   AX, ret+72(FP)
	RET
