// Code generated by command: go run main.go -out ../filters_amd64.s -stubs ../filters_stub_amd64.go -pkg simd. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

// func addIntoBlocks(dst []byte, src []byte)
// Requires: SSE2
TEXT ·addIntoBlocks(SB), NOSPLIT, $0-48
	MOVQ dst_base+0(FP), AX
	MOVQ src_base+24(FP), CX
	MOVQ dst_len+8(FP), DX
	ANDQ $-16, DX
	XORQ BX, BX

loop:
	CMPQ  BX, DX
	JGE   done
	MOVOU (AX)(BX*1), X0
	MOVOU (CX)(BX*1), X1
	PADDB X1, X0
	MOVOU X0, (AX)(BX*1)
	ADDQ  $0x10, BX
	JMP   loop

done:
	RET

// func subSumBlocks(dst []byte, a []byte, b []byte) uint64
// Requires: SSE2
TEXT ·subSumBlocks(SB), NOSPLIT, $0-80
	MOVQ dst_base+0(FP), AX
	MOVQ a_base+24(FP), CX
	MOVQ b_base+48(FP), DX
	MOVQ a_len+32(FP), BX
	ANDQ $-16, BX
	PXOR X0, X0
	PXOR X1, X1
	XORQ SI, SI

loop:
	CMPQ   SI, BX
	JGE    reduce
	MOVOU  (CX)(SI*1), X2
	MOVOU  (DX)(SI*1), X3
	PSUBB  X3, X2
	MOVOU  X2, (AX)(SI*1)
	PXOR   X3, X3
	PSUBB  X2, X3
	PMINUB X3, X2
	PSADBW X1, X2
	PADDQ  X2, X0
	ADDQ   $0x10, SI
	JMP    loop

reduce:
	MOVQ   X0, AX
	PSHUFD $0xee, X0, X0
	MOVQ   X0, CX
	ADDQ   CX, AX
	MOVQ   AX, ret+72(FP)
	RET

// func expandRGBToRGBABlocks(dst []byte, src []byte) int
// Requires: SSE2, SSSE3
TEXT ·expandRGBToRGBABlocks(SB), NOSPLIT, $0-56
	MOVQ  dst_base+0(FP), AX
	MOVQ  src_base+24(FP), CX
	MOVQ  src_len+32(FP), DX
	MOVOU expandShuffleMask<>+0(SB), X0
	MOVOU expandAlphaMask<>+0(SB), X1
	XORQ  BX, BX
	XORQ  SI, SI

loop:
	LEAQ   16(BX), DI
	CMPQ   DI, DX
	JG     done
	MOVOU  (CX)(BX*1), X2
	PSHUFB X0, X2
	POR    X1, X2
	MOVOU  X2, (AX)(SI*1)
	ADDQ   $0x0c, BX
	ADDQ   $0x10, SI
	JMP    loop

done:
	MOVQ BX, ret+48(FP)
	RET

DATA expandShuffleMask<>+0(SB)/16, $"\x00\x01\x02\x80\x03\x04\x05\x80\x06\a\b\x80\t\n\v\x80"
GLOBL expandShuffleMask<>(SB), RODATA|NOPTR, $16

DATA expandAlphaMask<>+0(SB)/16, $"\x00\x00\x00\xff\x00\x00\x00\xff\x00\x00\x00\xff\x00\x00\x00\xff"
GLOBL expandAlphaMask<>(SB), RODATA|NOPTR, $16

// func compactRGBAToRGBBlocks(dst []byte, src []byte) int
// Requires: SSE2, SSSE3
TEXT ·compactRGBAToRGBBlocks(SB), NOSPLIT, $0-56
	MOVQ  dst_base+0(FP), AX
	MOVQ  src_base+24(FP), CX
	MOVQ  dst_len+8(FP), DX
	MOVOU compactShuffleMask<>+0(SB), X0
	XORQ  BX, BX
	XORQ  SI, SI

loop:
	LEAQ   16(SI), DI
	CMPQ   DI, DX
	JG     done
	MOVOU  (CX)(BX*1), X1
	PSHUFB X0, X1
	MOVOU  X1, (AX)(SI*1)
	ADDQ   $0x10, BX
	ADDQ   $0x0c, SI
	JMP    loop

done:
	MOVQ SI, ret+48(FP)
	RET

DATA compactShuffleMask<>+0(SB)/16, $"\x00\x01\x02\x04\x05\x06\b\t\n\f\r\x0e\x80\x80\x80\x80"
GLOBL compactShuffleMask<>(SB), RODATA|NOPTR, $16
