// Code generated by command: go run main.go -out ../filters_amd64.s -stubs ../filters_stub_amd64.go -pkg simd. DO NOT EDIT.

//go:build !purego

package simd

// addIntoBlocks sets dst[i] += src[i] for the first len(dst)&^15 bytes (whole 16-byte blocks).
func addIntoBlocks(dst []byte, src []byte)

// subSumBlocks sets dst[i]=a[i]-b[i] and returns sum of abs8 over the first len(a)&^15 bytes.
func subSumBlocks(dst []byte, a []byte, b []byte) uint64
