//go:build !amd64 || purego

// Package simd provides SIMD-accelerated byte kernels for PNG filtering, with
// pure-Go fallbacks. On amd64 (without the purego build tag) the kernels use
// SSE2 assembly generated by ./asmgen; everywhere else this file is used.
package simd

// AddInto sets dst[i] += src[i] for i in range(len(dst)).
// len(src) must be >= len(dst).
func AddInto(dst, src []byte) {
	for i := range dst {
		dst[i] += src[i]
	}
}

// SubAndSumAbs sets dst[i] = a[i] - b[i] for i in range(len(a))
// and returns the sum of abs8(dst[i]),
// where abs8(d) interprets d as a signed int8 magnitude
// (d < 128 ? d : 256-d). len(dst) and len(b) must be >= len(a).
func SubAndSumAbs(dst, a, b []byte) int {
	sum := 0
	for i := range a {
		d := a[i] - b[i]
		dst[i] = d
		if d < 128 {
			sum += int(d)
		} else {
			sum += 256 - int(d)
		}
	}
	return sum
}
