//go:build !amd64 || purego

// Package simd provides SIMD-accelerated byte kernels for PNG filtering, with
// pure-Go fallbacks. On amd64 (without the purego build tag) the kernels use
// SSE2 assembly generated by ./asmgen; everywhere else this file is used.
package simd

// AddInto sets dst[i] += src[i] for i in range(len(dst)).
// len(src) must be >= len(dst).
func AddInto(dst, src []byte) {
	for i := range dst {
		dst[i] += src[i]
	}
}

// SubAndSumAbs sets dst[i] = a[i] - b[i] for i in range(len(a))
// and returns the sum of abs8(dst[i]),
// where abs8(d) interprets d as a signed int8 magnitude
// (d < 128 ? d : 256-d). len(dst) and len(b) must be >= len(a).
func SubAndSumAbs(dst, a, b []byte) int {
	sum := 0
	for i := range a {
		d := a[i] - b[i]
		dst[i] = d
		if d < 128 {
			sum += int(d)
		} else {
			sum += 256 - int(d)
		}
	}
	return sum
}

// ExpandRGBToRGBA writes npix RGBA pixels into dst from npix RGB pixels in src,
// setting every alpha byte to 0xFF.
// Requires len(dst) >= 4*npix and len(src) >= 3*npix.
func ExpandRGBToRGBA(dst, src []byte, npix int) {
	for i := 0; i < npix; i++ {
		dst[4*i+0] = src[3*i+0]
		dst[4*i+1] = src[3*i+1]
		dst[4*i+2] = src[3*i+2]
		dst[4*i+3] = 0xff
	}
}

// CompactRGBAToRGB writes npix RGB pixels into dst from npix RGBA pixels in src,
// dropping the alpha byte.
// Requires len(dst) >= 3*npix and len(src) >= 4*npix.
func CompactRGBAToRGB(dst, src []byte, npix int) {
	for i := 0; i < npix; i++ {
		dst[3*i+0] = src[4*i+0]
		dst[3*i+1] = src[4*i+1]
		dst[3*i+2] = src[4*i+2]
	}
}
